<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

require_once 'Mail.php';

function sendAdminEmail($subject, $body){
    $ci = &get_instance();

    $adminEmail = $ci->config->item('mgm_adminEmail');

    if($adminEmail == ""){
        $sim = new SimianGrid();
        $userList = $sim->allUsers();
        $addresses = array();
        foreach( $userList as $i => $u ){
            if($u->AccessLevel >= 250){
                array_push($addresses, $u->Email);
            }
        }
        die(json_encode(array('Success' => false, 'Message' => "admin email is blank, send to grid gods")));
    } else {
        //check if single or list of emails
        if(strpos($adminEmail, ",") !== false){
            $addresses = explode(",",$adminEmail);
        } else {
            $addresses = $adminEmail;
        }
    }
    sendEmail($addresses, $subject, $body);
}
		
function sendEmail($to, $subject, $body){
    $body.= "<br><br>This email has been automatically generated by the MOSES Grid Manager system, please do not reply.";
    
    $ci = &get_instance();

    $from = $ci->config->item('email_sourceAddress');
    $host = $ci->config->item('email_host');
    $port = $ci->config->item('email_port');
    $username = $ci->config->item('email_username');
    $password = $ci->config->item('email_password');

    $headers = array (
        'MIME-Version' => '1.0',
        'Content-type' => 'text/html; charset=iso-8859-1',
        'From' => $from,
        'To' => $to,
        'Subject' => $subject);
    $smtp = Mail::factory('smtp',
        array ('host' => $host,
            'port' => $port,
            'auth' => 'LOGIN',
            'username' => $username,
            'password' => $password));
    $mail = $smtp->send($to, $headers, $body);
	
    if( PEAR::isError($mail) ){
        return $mail->getMessage();
    } else {
        return true;
    }
}

function sendEmailAccountApproved($name, $email){
    $body = 'Congratulations ' . $name . ', Your MOSES account has been approved.<br><br>';
    $body.= 'You can now log into the MOSES Grid using the name and password you registered with.<br>';
    $body.= 'You can connect using the MOSES client, which is for Windows only.  Download it from <a href="https://cloud.militarymetaverse.org/public.php?service=files&t=7d883d2108341ba859eae3ecd45a98c3">https://cloud.militarymetaverse.org/public.php?service=files&t=7d883d2108341ba859eae3ecd45a98c3</a><br>';
    $body.= "If you are on a different platform, or wish to use another viewer, the login uri for the MOSES Grid is:<br>";
    $body.= "moses.militarymetaverse.org <br><br>";
    $body.= "We look forward to seeing you in world.";
    sendEmail($email, "MOSES Account Approved", $body);
}

function sendEmailRegistrationSuccessful($name, $email){
    $body = $name . ":<br>Thank you for registering for a MOSES account.  If you are approved you will recieve an addtional email from us notifying you of where you can download the MOSES client.";
    sendEmail($email, "MOSES Application Received", $body);
}

function sendEmailUserRegistered($name, $email){
    $body = "MOSES Admin:<br>A new user account application has been receieved with the name " . $name . " and the email " . $email . ".<br>Please review the applicant in the pending users tab in your MGM instance.";
    sendAdminEmail("MGM Application Received", $body);
}

function sendEmailAccountDenied($email, $reason){
    $body = "Your account application for MOSES has been denied.  The administrators of this MOSES instance have sent you the message:<br>";
    $body.= $reason;
    sendEmail($email, "Moses Application Denied", $body);
}

function sendPasswordReset($email, $token){
    $body = "Your password reset request has been processed.  Please visit militarymetaverse.org, and using the forgot password button, complete the second form using the following token:<br>";
    $body.= $token;
    sendEmail($email, "MOSES Password Recovery", $body);
}

function sendSaveOarCompleteEmail($email, $filename){
    $body = "Your save oar task has completed successfully.  Please download your file " . $filename . " from your user task list";
    sendEmail($email, "MOSES save oar complete", $body);
}

function sendSaveIarCompleteEmail($email, $filename){
    $body = "Your save iar task has completed successfully.  Please download your file " . $filename . " from your user task list";
    sendEmail($email, "MOSES save iar complete", $body);
}

?>
